### ISSUE TITLE
Support moonrise/dark theme

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#118]
The Downloads of moonrise theme are impressing. So at least a test should be done if the theme looks fine with EGradle

### TODO:
- [x] Editor coloring
   - [x] User must be able to customize colours
   - [x] Provide defaults settings for white and dark theme (neon)
   - [x] Check eclipse color theme mentioned in #163 and in #118 

- [x] Icon issue
   Change the gradle icon , see #164 

Created an extra issue #167 for eclipse-theme support/contribution

**Comment by de-jcup** [comment]
Linux with GTK tested

- [x] icons could be better, but still okay, maybe the Gradle-OG icon should contain white inside and not transparent color: 
![egrade-moonrise-0](https://cloud.githubusercontent.com/assets/11644753/19886110/2a075920-a022-11e6-96c2-8b94536ea651.png)

- [x] console output - launch mechanism, moonrise does not correct support launch console colouring (I tested also a simple java output) but turns always to white backround. But dark theme under eclipse neon works fine on launching.  On egradle system console both work correct and look good :
![egrade-moonrise-1](https://cloud.githubusercontent.com/assets/11644753/19885854/2e99e120-a021-11e6-96ce-7612279cbbba.png)
- [x] editor - hmmm. could be better. But funny: The colors I did hard coded use (copies of java editor normal theme) - are looking great, but the color from default style is look bad (black parts)
![egrade-moonrise-2](https://cloud.githubusercontent.com/assets/11644753/19886262/bf3c1d78-a022-11e6-974f-6817d966a572.png)

**Comment by de-jcup** [comment]
The easiest way would be
- [ ]  Make colours configurable (also the default color - black...)
- [ ] Change the gradle icon - use white inside instead of transparent color

**Comment by de-jcup** [comment]
Customization of syntax colouring could be done like in java editor:

![image](https://cloud.githubusercontent.com/assets/11644753/21137716/11e261d0-c12b-11e6-930b-e4a394c11574.png)

Should be a sub entry point under Editor as well (and maybe the preview also)

**Comment by paulvi** [comment]
You may need to add color preferences and contribute to https://github.com/eclipse-color-theme/eclipse-color-theme

**Comment by de-jcup** [comment]
With last commit now configurable in preferences:

![image](https://cloud.githubusercontent.com/assets/11644753/21181140/b97faeee-c1fc-11e6-8738-20ba0e3ebbb8.png)

**Comment by de-jcup** [comment]
Result now as described at https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/editor.html#syntax_highlight_dark_theme_defaults

![image](https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/images/egradle-syntax-coloring-dark-theme-defaults.png)
