### ISSUE TITLE
EGradle Editor: code completion (gradle DSL)

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#120]
Basic code completion for gradle DSL - will do **no** method operations , but provide element/closure prosposals 

## Code completion
![image](https://cloud.githubusercontent.com/assets/11644753/23013842/b6e3fbc4-f42c-11e6-9f0a-3512ef10f8ca.png)

## Tooltips
![image](https://cloud.githubusercontent.com/assets/11644753/22991534/d7b252e4-f3bc-11e6-9a00-b1e4c142d628.png)

**TODO**
- [x] tasks.withType(type){}
- [x] public methods only
- [x] public "properties" only

**Comment by wolfgang-ch** [comment]
Does this also include mouse hover support to show more information about the hovered item in a tooltip?

**Comment by de-jcup** [comment]
@wolfgang-ch : I created issue #178 for this. Changed title for this issue

**Comment by de-jcup** [comment]
![code-completion-basically-working-120](https://cloud.githubusercontent.com/assets/11644753/21660135/73c4f322-d2ce-11e6-98f2-e1cf5e3161c7.png)

**Comment by de-jcup** [comment]
Trying another approach:
- forked gradle project : https://github.com/de-jcup/gradle
- gradle does generate the complete dsl documentation by gradle build
  so startet egradle dsl task in subproject "docs" in fork.
  see also https://github.com/de-jcup/gradle/issues/1
  So a dsl description in xml shall be generated to be used in egradle

- the former approach of path resolution will not work.
- So new approach will do correct by type resolving etc. will be also base for documentation hoovering etc.

**Comment by de-jcup** [comment]
@wolfgang-ch : EGradle 1.3.0 is released and contains (basic) code completion and tooltips now.

**Comment by wolfgang-ch** [comment]
It was a longer way to go and many many steps to implement this feature but finally it is done 🥇
