### ISSUE TITLE
Deployment V1.1.3

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#139]
**Update eclipse documentation**
- [x] Link to other gradle files inside editor
- [x] CTRL + SHIFT + P in editor #124 
- [x] CTRL + SHIFT + P - preferences #124 
- [x] Quick outline view #122
- [x] Check if other pictures have to be updated (e.g. like editor preferences)
- [x] Integrate links to youtube playlist
- [x] Remove "...new features are planned (e.g. link to included files)"
- [x] change EGradle root project by context menu #152 
- [x] Direct  EGradle import command in context menu for current gradle projects #154  

**Update wiki**
- [ ] Feature overview update

**Other**
- [ ] Upload eclipse market place
- [ ] Update documentation in eclipse market place
- [ ] Provide picture of quick outline
