### ISSUE TITLE
Deployment 2.0

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#248]
# DONE
- [x] Test JUnit Integration is added per default on installation (but can be turned off ).
       This must be tested before official release to market place. The PDE does NOT provide Junit Integration
       when starting with feature IDE only!
- [x] Test MAC works with New Project wizard ( #161 )
- [x] Upgrade installation documentation (editor)
- [x] Upgrade installation documentation (gradle setup changed)
- [x] Upgrade installation documentation (remove overview page and insert former content to toc.html)
- [x] VirtualRotProject recreate currently not working. Throws exception, must be fixed.
- [x] It seems build artifacts (1.3.1) did contain sources too. Should be removed from build with 2.0

# TODO
- [x] Documentation of #258 ("api guide"
      subpage, describing the extension point usable by other IDEs)
- [x] Execute Tests at https://github.com/de-jcup/egradle/projects/3

- [x] Create market place entry for "EGradle editor"
- [x] Execute Deployment Steps at https://github.com/de-jcup/egradle/projects/4
