### ISSUE TITLE
Test gradle 4.0 works with EGradle

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#270]
gradle 4.0 was just released
https://docs.gradle.org/4.0/release-notes.html

## TODO
- [x] Change build of EGradle itself: so test it can be build with gradle 4.0
- [x] Check Junit importer works with gradle 4.0 again (avoid something like #259)
- [x] Check new project wizard templates do work with gradle4.0 (does automatically check
     that EGradle import wizard works)
